environment:
  ENVIRONMENT: "${ENVIRONMENT}"
packages:
    - name: v1
      shared: false
      functions:
        - name: quests
          binary: true
          main: "main"
          runtime: go:1.20
          web: true
          environment:
            POSTHOG_API_URL: "${POSTHOG_API_URL}"
            POSTHOG_API_KEY: "${POSTHOG_API_KEY}"
            POSTHOG_PROJECT_ID: "${POSTHOG_PROJECT_ID}"
          limits:
            timeout: 30000 # 30 seconds in milliseconds

        - name: swagger
          binary: true
          main: "main"
          runtime: go:1.20
          web: true

        - name: versions
          binary: true
          main: "main"
          runtime: go:1.20
          web: true
