environment:
  ENVIRONMENT: "${ENVIRONMENT}"
packages:
    - name: achievements
      shared: false
      functions:
        - name: quests
          binary: true
          main: "main"
          runtime: go:1.20
          web: true
          webSecure: false

    - name: system
      shared: false
      functions:
        - name: versions
          binary: true
          main: "main"
          runtime: go:1.20
          web: true
          webSecure: false
