environment:
  ENVIRONMENT: "${ENVIRONMENT}"
packages:
    - name: quests
      shared: false
      functions:
        - name: daily
          binary: true
          main: "main"
          runtime: go:1.20
          web: true
          webSecure: false

    - name: system
      shared: false
      functions:
        - name: versions
          binary: true
          main: "main"
          runtime: go:1.20
          web: true
          webSecure: false
