FROM golang:1.22-alpine AS composer

ENV GO111MODULE=on

# install the required dependencies: CompileDaemon, bash and make
RUN apk update \
    && apk add --no-cache bash make
RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /usr/app

CMD ["/bin/sh", "-c", "./scripts/start_service.sh ${SERVICE_NAME}"]
